### PR TITLE
Migrated to Swift 3 and updated to recommended settings.

### PR DESCRIPTION
**Pull request by JettF**
I migrated your project to Swift 3! Mind pushing a new version so I can rely on it?

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Hope to see this pulled in soon! I'm depending on this fork in my projects and it's working well.

**Review by AnthonyMDev — APPROVED** [review]

**Comment by JettF** [comment]
Thanks for merging! Any idea when you can push a new version?

**Comment by bradhilton** [comment]
I just a pushed a new version to the CocoaPods trunk.

**Comment by JettF** [comment]
Thank you!

**Comment by AnthonyMDev** [comment]
Thanks @bradhilton!

**Pull request merged**
